#!/usr/bin/env Rscript
# =============================================================================
# Generate a synthetic (fake) registry-like dataset in the input format of the
# pipeline. No real data, and no parameters estimated from real data, are used:
# the ground-truth network is a random sparse multivariate Hawkes process.
#
# Output (in data/synthetic/ by default):
#   persons.csv        person_id, sex, birth_date
#   events.csv         person_id, event_id, event_date
#   ground_truth/      true baseline rates and integrated excitation matrix,
#                      to check structural recovery on the synthetic data
#
# Event types are those of data/event_definitions.csv (29 CMD + 38 RISK).
#
# Usage (from the repository root):
#   Rscript synthetic/generate_synthetic_data.R [n_persons] [seed] [out_dir] [network_seed]
#
# `network_seed` fixes the ground-truth network and `seed` the simulated
# individuals: datasets with the same network_seed and different seeds mimic
# two cohorts generated by the same disease network (e.g. discovery and
# replication).
# =============================================================================

args <- commandArgs(trailingOnly = TRUE)
n_persons <- if (length(args) >= 1) as.integer(args[1]) else 5000L
seed      <- if (length(args) >= 2) as.integer(args[2]) else 2026L
out_dir   <- if (length(args) >= 3) args[3] else file.path("data", "synthetic")
network_seed <- if (length(args) >= 4) as.integer(args[4]) else 2026L

set.seed(network_seed)

defs <- read.csv(file.path("data", "event_definitions.csv"), stringsAsFactors = FALSE)
D    <- nrow(defs)

# ---- Ground-truth Hawkes process (time unit: months since age 40) ----------
T_max    <- 480                              # age 40 to 80
landmark <- c(0, 6, 12, 24, 36, 60, 90, 120) # Gaussian basis centres (months)
w        <- 12                               # basis bandwidth (months)
L        <- length(landmark)
density  <- 0.15                             # share of non-zero directed pairs
rho      <- 0.5                              # spectral radius of integrated A
n_max    <- 120                              # maximum events per individual

# A[cause, l, effect]: weight of basis l for the effect of `cause` on `effect`
mask  <- matrix(runif(D * D) < density, D, D)
diag(mask) <- runif(D) < 0.5                 # some self-excitation
decay <- 0.6^(seq_len(L) - 1)                # short lags dominate
A <- array(0, c(D, L, D))
for (i in seq_len(D)) for (j in seq_len(D)) {
  if (mask[i, j]) A[i, , j] <- runif(1, 0.3, 1) * decay
}
# integrated excitation (each Gaussian basis integrates to ~1 over the lag)
A_int <- apply(A, c(1, 3), sum)
A     <- A * rho / max(Mod(eigen(A_int, only.values = TRUE)$values))
A_int <- apply(A, c(1, 3), sum)

# baseline rates: CMD events more frequent than RISK, heterogeneous
base_w <- rgamma(D, shape = 1.5) * ifelse(defs$group == "CMD", 2, 1)
mu     <- base_w / sum(base_w) * 8 * (1 - rho) / T_max   # ~8 events / person

set.seed(seed)                               # individuals

g_max <- 1 / (sqrt(2 * pi) * w)              # maximum of a Gaussian basis
basis <- function(dt) exp(-outer(dt, landmark, "-")^2 / (2 * w^2)) / (sqrt(2 * pi) * w)

# per-cause upper bound of the excitation it can add to the total intensity
bound_cause <- apply(A, 1, sum) * g_max

simulate_person <- function() {
  t <- 0; times <- numeric(0); marks <- integer(0); bound_hist <- 0
  repeat {
    M <- sum(mu) + bound_hist
    t <- t + rexp(1, M)
    if (t > T_max || length(times) >= n_max) break
    lam <- mu
    if (length(times) > 0) {
      G <- basis(t - times)                  # n_events x L
      for (k in seq_along(times)) lam <- lam + as.vector(G[k, ] %*% A[marks[k], , ])
    }
    if (runif(1) * M <= sum(lam)) {
      m <- sample.int(D, 1, prob = lam)
      times <- c(times, t); marks <- c(marks, m)
      bound_hist <- bound_hist + bound_cause[m]
    }
  }
  list(time = times, mark = marks)
}

# ---- Simulate individuals and convert to registry-like dates ---------------
cat(sprintf("Simulating %d individuals, %d event types (seed %d, network seed %d) ...\n", n_persons, D, seed, network_seed))
sims <- vector("list", n_persons)
for (p in seq_len(n_persons)) sims[[p]] <- simulate_person()

person_id  <- sprintf("P%06d", seq_len(n_persons))
birth_date <- as.Date("1920-01-01") + sample(0:(as.numeric(as.Date("1975-12-31") - as.Date("1920-01-01"))),
                                             n_persons, replace = TRUE)
persons <- data.frame(person_id  = person_id,
                      sex        = sample(c("F", "M"), n_persons, replace = TRUE, prob = c(0.45, 0.55)),
                      birth_date = birth_date)

days_per_month <- 365.25 / 12
events <- do.call(rbind, lapply(seq_len(n_persons), function(p) {
  s <- sims[[p]]
  if (length(s$time) == 0) return(NULL)
  data.frame(person_id  = person_id[p],
             event_id   = defs$event_id[s$mark],
             event_date = birth_date[p] + round((40 * 12 + s$time) * days_per_month))
}))

# ---- Write -----------------------------------------------------------------
dir.create(file.path(out_dir, "ground_truth"), recursive = TRUE, showWarnings = FALSE)
write.csv(persons, file.path(out_dir, "persons.csv"), row.names = FALSE)
write.csv(events,  file.path(out_dir, "events.csv"),  row.names = FALSE)
write.csv(data.frame(event_id = defs$event_id, mu = mu),
          file.path(out_dir, "ground_truth", "baseline_rates.csv"), row.names = FALSE)
dimnames(A_int) <- list(defs$event_id, defs$event_id)   # rows: cause, columns: effect
write.csv(A_int, file.path(out_dir, "ground_truth", "excitation_integrated.csv"))
writeLines(c(sprintf("seed=%d", seed), sprintf("network_seed=%d", network_seed), sprintf("n_persons=%d", n_persons),
             sprintf("landmarks=%s", paste(landmark, collapse = ",")), sprintf("w=%g", w),
             sprintf("density=%g", density), sprintf("spectral_radius=%g", rho)),
           file.path(out_dir, "ground_truth", "settings.txt"))

n_ev <- table(factor(events$person_id, levels = person_id))
cat(sprintf("Done: %d events; events per person mean %.1f (median %d, max %d); %d persons with >=3 events\n",
            nrow(events), mean(n_ev), as.integer(median(n_ev)), max(n_ev), sum(n_ev >= 3)))
